### PR TITLE
Pull PDF metadata

### PR DESCRIPTION
**Pull request by mDandini**
This change pulls metadata from PDF files when they're accessed by UNC and WAF brokers. The PDF metadata is stored as standard Dublin Core XML metadata, and links to the PDF files are provided in the GeoPortal catalog website.

### CODE REVIEW

**Comment by pandzel** [comment]
Great, but I am going to ask you to do few more things.

1. Let's take a look at UncFile.java but similar principles apply to WafFile.java as well. In UncFile.java:73 call to PdfUtils.readMetadata(input) will exhaust the stream and no more bytes in it. So, if UncFile.java:75 metaProps == null, algorithm proceeds to UncFile.java:91 where IOUtils.toByteArray(input) will attempt to read that stream again but the stream is empty now, so the entire things fails.

2. By design, any input broker should only reach out to the associated end-point, obtain a raw data in the form of array of bytes and refrain from doing any processing like parsing pdf. This is important from the performance point of view. There is another concept called "transformer" which supposed to be responsible for doing such extra tasks as desired, but since we don't have an effective UI for transformers, certain work-around's are inevitable. Eventually, all code as yours will be implemented as a transformer, but for now I would recommend to refactor the code as:

- create a separate class (lets say: PdfProcessor) with a single method in it (let it be 'transform' method), taking array of bytes as an input and returning array of bytes or null
- move extracting metadata from pdf into that 'transform' method; make it so the assertion from the line UncFile.java:72 is part of the code of the 'transform' method
- create a final static instance of the PdfProcessor as a class member of UncFile.java,
- replace all the pdf-related code inside UncFile.java with a single call to the 'transform' method,
- make this optional, so the user can choose whether process pdf or not at the time of defining broker (very similar to some other brokers which have check boxes to 'Emit JSON' or 'Emit XML')

3. Regardless whether pdf processing in step 2. will happen or not, attaching original data is still very important. This is because some of the output brokers might be interested in that raw data, for example Portal for ArcGIS has ability to accept and store pdf files (harvester doesn't support that yet, though). So, having together:

ref.addContent(MimeType.APPLICATION_XML, bytes)
ref.addContent(contentType, IOUtils.toByteArray(input))

is still important.

**Comment by pandzel** [comment]
Is there any reason to use 2.0.4 of org.apache.pdf dependency? There is a newer one: 2.0.9.

**Comment by mDandini** [comment]
Thank you for looking at this. I can make the changes as you described, but they do raise another question: would it be better to have the option to transform the PDFs on the *output* broker instead of the input?

That way, the input brokers (e.g. UNC, WAF) would only focus on getting the raw data, and the output brokers can decide if they want to do any transformation.

**Comment by pandzel** [comment]
Regarding the question

**Pull request merged**
